# -*- coding: utf-8 -*-
import logging
from flask import Blueprint, request, jsonify
from src.models.user import db, User
from src.models.game import GameRoom, Player, generate_room_code

logger = logging.getLogger(__name__)
game_bp = Blueprint("game", __name__)

@game_bp.route("/rooms", methods=["GET"])
def list_rooms():
    """Lists available game rooms (status = waiting)."""
    try:
        # Query rooms that are waiting for players
        waiting_rooms = GameRoom.query.filter_by(status="waiting").order_by(GameRoom.created_at.desc()).all()
        
        rooms_data = []
        for room in waiting_rooms:
            # Get current player count using the relationship
            player_count = room.players.count() # Count players associated with the room
            host_username = room.host.username if room.host else "Unknown"
            rooms_data.append({
                "room_code": room.room_code,
                "game_type": room.game_type,
                "host_id": room.host_id,
                "host_username": host_username,
                "max_players": room.max_players,
                "current_players_count": player_count,
                "status": room.status,
                "created_at": room.created_at.isoformat()
            })
            
        return jsonify(rooms_data), 200
    except Exception as e:
        logger.error(f"Error listing rooms: {e}", exc_info=True)
        return jsonify({"error": "Failed to retrieve game rooms"}), 500

@game_bp.route("/rooms", methods=["POST"])
def create_room():
    """Creates a new game room."""
    data = request.get_json()
    if not data:
        return jsonify({"error": "Invalid request body"}), 400

    host_id = data.get("host_id")
    game_type = data.get("game_type")
    max_players = data.get("max_players")

    if not host_id or not game_type or not max_players:
        return jsonify({"error": "Missing required fields: host_id, game_type, max_players"}), 400

    try:
        max_players = int(max_players)
        if max_players < 2: # Example minimum players
             return jsonify({"error": "Maximum players must be at least 2"}), 400
    except ValueError:
        return jsonify({"error": "max_players must be an integer"}), 400

    # Verify host user exists
    host = User.query.get(host_id)
    if not host:
        return jsonify({"error": f"Host user with ID {host_id} not found"}), 404

    try:
        # Create new room
        new_room = GameRoom(
            host_id=host_id,
            game_type=game_type,
            max_players=max_players,
            status="waiting" # Initial status
            # room_code is generated by default
        )
        db.session.add(new_room)
        db.session.flush() # Flush to get the new_room.id

        # Automatically add the host as the first player
        host_player = Player(user_id=host_id, room_id=new_room.id)
        db.session.add(host_player)
        
        db.session.commit()
        logger.info(f"New room created: {new_room.room_code} by host {host.username}")

        # Return details of the created room
        return jsonify({
            "message": "Room created successfully",
            "room_code": new_room.room_code,
            "game_type": new_room.game_type,
            "host_id": new_room.host_id,
            "max_players": new_room.max_players,
            "status": new_room.status
        }), 201

    except Exception as e:
        db.session.rollback()
        logger.error(f"Error creating room: {e}", exc_info=True)
        return jsonify({"error": "Failed to create game room"}), 500

# Add more routes as needed, e.g., GET /rooms/<room_code> to get details of a specific room

